=== MarcSendraSapena/tema03/dtd1.dtd
<!ELEMENT minecraftItems (item+)>
<!ELEMENT item (id, name, type, rarity, damage?, description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT rarity (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ATTLIST minecraftItems lang CDATA #REQUIRED>
<!ATTLIST type
    values (arma | herramienta | bloque) #REQUIRED>
<!ATTLIST rarity
    values (común | raro | épico) #REQUIRED>

=== MarcSendraSapena/tema03/Untitled-1bueno.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minecraftItems SYSTEM "dtd1.dtd">
<minecraftItems lang="es">

    <item id="i1">
        <name>Mesa encantamientos</name>
        <type>Objeto</type>
        <rarity>Raro</rarity>
        <damage>No aplica</damage>
        <description>Sirve para encantar</description>  
    </item>

    </item  id="i2">
        <name>Mesa encantamientos</name>
        <type>Objeto</type>
        <rarity>Raro</rarity>
        <damage>No aplica</damage>
        <description>Sirve para encantar</description>  
    </item>
    
</minecraftItems>
